@startuml DeploymentDiagram

node WebServer <<Device>> {
    node Node.js <<Execution Environment>> {
        component Middleware
        component Routes
        component Services
        component Managers
        component Queries
        artifact index.js
        artifact server.js
    }
}

node Android <<Device>> {
    component Flutter <<UI>>
}

database PostgreSQL <<Database>>

node PaymentService {

}

WebServer -right- PostgreSQL:<<ORM>>
WebServer -- Android :<<HTTP:8080>>
WebServer -left- PaymentService :<<HTTP:8080>>

@enduml