@startuml ERD

enum ROLES {
    SUPERADMIN
    ADMIN
    TABLE
}

enum ORDER_STATUS {
    PENDING
    CHECKOUT
    PAID
    QUEUE
    PROCESSING
    READY
    RESOLVED
}

entity user {
    id: int <<PK>>
    --
    name: varchar
    role: ROLES
}

entity user_account {
    user_id: number <<PK>>
    --
    password: string
    token: string
}

entity order {
    id: number <<PK>>
    --
    created_at: date
    user_id: number <<FK>>
    total: number
    status: ORDER_STATUS
    cancelled_at: date
}

entity order_item {
    order_id: number <<FK>>
    item_id: number <<FK>>
}

entity item {
    id: number <<PK>>
    --
    category_id: number <<FK>>
    name: string
    description: string
    price: number
}

entity category {
    id: number <<PK>>
    --
    category_id: number
    name: string
}

user ||--|| user_account
user }|--o{ order
order ||--o{ order_item
item ||--o{ order_item
category ||--|{ item

@enduml